# Generated by Django 6.0.2 on 2026-03-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.IntegerField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('lumière', models.IntegerField()),
                ('periode', models.CharField(max_length=10)),
                ('servo', models.IntegerField()),
                ('pompe', models.CharField(max_length=10)),
                ('led', models.CharField(default='OFF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='blogPost',
        ),
    ]
