# Generated by Django 6.0.2 on 2026-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='serre',
            name='led',
            field=models.CharField(default='OFF', max_length=10),
        ),
        migrations.AddField(
            model_name='serre',
            name='pompe_lock',
            field=models.IntegerField(default=600),
        ),
    ]
