# Generated by Django 6.0.2 on 2026-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serre_pompe_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
