# Generated by Django 6.0.2 on 2026-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logs_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='serre',
            name='eau',
            field=models.IntegerField(default=100000),
        ),
    ]
