# Generated by Django 6.0.2 on 2026-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_serre_eau'),
    ]

    operations = [
        migrations.AddField(
            model_name='serre',
            name='debit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serre',
            name='pump_on_time',
            field=models.FloatField(default=0.0),
        ),
    ]
