# Generated by Django 6.0.3 on 2026-03-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_photo_path_photo_created_at_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
